version: "3"

services:
    guardian:
        image: handsonsecurity/seed-ubuntu:large
        container_name: network-guardian
        tty: true
        cap_add:
                - ALL
        privileged: true
        volumes:
                - ./volumes:/volumes
        network_mode: host

    sender:
        image: handsonsecurity/seed-ubuntu:large
        container_name: sender-10.9.0.2
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2
        volumes:
                - ./volumes:/volumes
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    proxyA:
        image: handsonsecurity/seed-ubuntu:large
        container_name: proxyA-10.9.0.3
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.3
        volumes:
                - ./volumes:/volumes
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    proxyB:
        image: handsonsecurity/seed-ubuntu:large
        container_name: proxyB-10.9.0.4
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.4
        volumes:
                - ./volumes:/volumes
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

    endUser:
        image: handsonsecurity/seed-ubuntu:large
        container_name: endUser-10.9.0.5
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5
        volumes:
                - ./volumes:/volumes
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null
                 "

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
